package com.gap.pino_copy.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gap.pino_copy.db.objectmodel.DeviceSetting;
import com.gap.pino_copy.db.objectmodel.User;
import com.gap.pino_copy.db.objectmodel.UserPermission;
import com.gap.pino_copy.db.objectmodel.AppUser;
import com.gap.pino_copy.db.objectmodel.ChatGroup;
import com.gap.pino_copy.db.objectmodel.ChatGroupMember;
import com.gap.pino_copy.db.objectmodel.ChatMessage;
import com.gap.pino_copy.db.objectmodel.ComplaintReport;
import com.gap.pino_copy.db.objectmodel.SurveyForm;
import com.gap.pino_copy.db.objectmodel.SurveyFormQuestion;
import com.gap.pino_copy.db.objectmodel.SurveyFormQuestionTemp;
import com.gap.pino_copy.db.objectmodel.Form;
import com.gap.pino_copy.db.objectmodel.FormQuestion;
import com.gap.pino_copy.db.objectmodel.FormAnswer;
import com.gap.pino_copy.db.objectmodel.FormItemAnswer;
import com.gap.pino_copy.db.objectmodel.FormTemp;
import com.gap.pino_copy.db.objectmodel.AttachFile;
import com.gap.pino_copy.db.objectmodel.FormQuestionGroup;
import com.gap.pino_copy.db.objectmodel.FormQuestionGroupForm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceSettingDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userPermissionDaoConfig;
    private final DaoConfig appUserDaoConfig;
    private final DaoConfig chatGroupDaoConfig;
    private final DaoConfig chatGroupMemberDaoConfig;
    private final DaoConfig chatMessageDaoConfig;
    private final DaoConfig complaintReportDaoConfig;
    private final DaoConfig surveyFormDaoConfig;
    private final DaoConfig surveyFormQuestionDaoConfig;
    private final DaoConfig surveyFormQuestionTempDaoConfig;
    private final DaoConfig formDaoConfig;
    private final DaoConfig formQuestionDaoConfig;
    private final DaoConfig formAnswerDaoConfig;
    private final DaoConfig formItemAnswerDaoConfig;
    private final DaoConfig formTempDaoConfig;
    private final DaoConfig attachFileDaoConfig;
    private final DaoConfig formQuestionGroupDaoConfig;
    private final DaoConfig formQuestionGroupFormDaoConfig;

    private final DeviceSettingDao deviceSettingDao;
    private final UserDao userDao;
    private final UserPermissionDao userPermissionDao;
    private final AppUserDao appUserDao;
    private final ChatGroupDao chatGroupDao;
    private final ChatGroupMemberDao chatGroupMemberDao;
    private final ChatMessageDao chatMessageDao;
    private final ComplaintReportDao complaintReportDao;
    private final SurveyFormDao surveyFormDao;
    private final SurveyFormQuestionDao surveyFormQuestionDao;
    private final SurveyFormQuestionTempDao surveyFormQuestionTempDao;
    private final FormDao formDao;
    private final FormQuestionDao formQuestionDao;
    private final FormAnswerDao formAnswerDao;
    private final FormItemAnswerDao formItemAnswerDao;
    private final FormTempDao formTempDao;
    private final AttachFileDao attachFileDao;
    private final FormQuestionGroupDao formQuestionGroupDao;
    private final FormQuestionGroupFormDao formQuestionGroupFormDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceSettingDaoConfig = daoConfigMap.get(DeviceSettingDao.class).clone();
        deviceSettingDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userPermissionDaoConfig = daoConfigMap.get(UserPermissionDao.class).clone();
        userPermissionDaoConfig.initIdentityScope(type);

        appUserDaoConfig = daoConfigMap.get(AppUserDao.class).clone();
        appUserDaoConfig.initIdentityScope(type);

        chatGroupDaoConfig = daoConfigMap.get(ChatGroupDao.class).clone();
        chatGroupDaoConfig.initIdentityScope(type);

        chatGroupMemberDaoConfig = daoConfigMap.get(ChatGroupMemberDao.class).clone();
        chatGroupMemberDaoConfig.initIdentityScope(type);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        complaintReportDaoConfig = daoConfigMap.get(ComplaintReportDao.class).clone();
        complaintReportDaoConfig.initIdentityScope(type);

        surveyFormDaoConfig = daoConfigMap.get(SurveyFormDao.class).clone();
        surveyFormDaoConfig.initIdentityScope(type);

        surveyFormQuestionDaoConfig = daoConfigMap.get(SurveyFormQuestionDao.class).clone();
        surveyFormQuestionDaoConfig.initIdentityScope(type);

        surveyFormQuestionTempDaoConfig = daoConfigMap.get(SurveyFormQuestionTempDao.class).clone();
        surveyFormQuestionTempDaoConfig.initIdentityScope(type);

        formDaoConfig = daoConfigMap.get(FormDao.class).clone();
        formDaoConfig.initIdentityScope(type);

        formQuestionDaoConfig = daoConfigMap.get(FormQuestionDao.class).clone();
        formQuestionDaoConfig.initIdentityScope(type);

        formAnswerDaoConfig = daoConfigMap.get(FormAnswerDao.class).clone();
        formAnswerDaoConfig.initIdentityScope(type);

        formItemAnswerDaoConfig = daoConfigMap.get(FormItemAnswerDao.class).clone();
        formItemAnswerDaoConfig.initIdentityScope(type);

        formTempDaoConfig = daoConfigMap.get(FormTempDao.class).clone();
        formTempDaoConfig.initIdentityScope(type);

        attachFileDaoConfig = daoConfigMap.get(AttachFileDao.class).clone();
        attachFileDaoConfig.initIdentityScope(type);

        formQuestionGroupDaoConfig = daoConfigMap.get(FormQuestionGroupDao.class).clone();
        formQuestionGroupDaoConfig.initIdentityScope(type);

        formQuestionGroupFormDaoConfig = daoConfigMap.get(FormQuestionGroupFormDao.class).clone();
        formQuestionGroupFormDaoConfig.initIdentityScope(type);

        deviceSettingDao = new DeviceSettingDao(deviceSettingDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userPermissionDao = new UserPermissionDao(userPermissionDaoConfig, this);
        appUserDao = new AppUserDao(appUserDaoConfig, this);
        chatGroupDao = new ChatGroupDao(chatGroupDaoConfig, this);
        chatGroupMemberDao = new ChatGroupMemberDao(chatGroupMemberDaoConfig, this);
        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);
        complaintReportDao = new ComplaintReportDao(complaintReportDaoConfig, this);
        surveyFormDao = new SurveyFormDao(surveyFormDaoConfig, this);
        surveyFormQuestionDao = new SurveyFormQuestionDao(surveyFormQuestionDaoConfig, this);
        surveyFormQuestionTempDao = new SurveyFormQuestionTempDao(surveyFormQuestionTempDaoConfig, this);
        formDao = new FormDao(formDaoConfig, this);
        formQuestionDao = new FormQuestionDao(formQuestionDaoConfig, this);
        formAnswerDao = new FormAnswerDao(formAnswerDaoConfig, this);
        formItemAnswerDao = new FormItemAnswerDao(formItemAnswerDaoConfig, this);
        formTempDao = new FormTempDao(formTempDaoConfig, this);
        attachFileDao = new AttachFileDao(attachFileDaoConfig, this);
        formQuestionGroupDao = new FormQuestionGroupDao(formQuestionGroupDaoConfig, this);
        formQuestionGroupFormDao = new FormQuestionGroupFormDao(formQuestionGroupFormDaoConfig, this);

        registerDao(DeviceSetting.class, deviceSettingDao);
        registerDao(User.class, userDao);
        registerDao(UserPermission.class, userPermissionDao);
        registerDao(AppUser.class, appUserDao);
        registerDao(ChatGroup.class, chatGroupDao);
        registerDao(ChatGroupMember.class, chatGroupMemberDao);
        registerDao(ChatMessage.class, chatMessageDao);
        registerDao(ComplaintReport.class, complaintReportDao);
        registerDao(SurveyForm.class, surveyFormDao);
        registerDao(SurveyFormQuestion.class, surveyFormQuestionDao);
        registerDao(SurveyFormQuestionTemp.class, surveyFormQuestionTempDao);
        registerDao(Form.class, formDao);
        registerDao(FormQuestion.class, formQuestionDao);
        registerDao(FormAnswer.class, formAnswerDao);
        registerDao(FormItemAnswer.class, formItemAnswerDao);
        registerDao(FormTemp.class, formTempDao);
        registerDao(AttachFile.class, attachFileDao);
        registerDao(FormQuestionGroup.class, formQuestionGroupDao);
        registerDao(FormQuestionGroupForm.class, formQuestionGroupFormDao);
    }
    
    public void clear() {
        deviceSettingDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        userPermissionDaoConfig.getIdentityScope().clear();
        appUserDaoConfig.getIdentityScope().clear();
        chatGroupDaoConfig.getIdentityScope().clear();
        chatGroupMemberDaoConfig.getIdentityScope().clear();
        chatMessageDaoConfig.getIdentityScope().clear();
        complaintReportDaoConfig.getIdentityScope().clear();
        surveyFormDaoConfig.getIdentityScope().clear();
        surveyFormQuestionDaoConfig.getIdentityScope().clear();
        surveyFormQuestionTempDaoConfig.getIdentityScope().clear();
        formDaoConfig.getIdentityScope().clear();
        formQuestionDaoConfig.getIdentityScope().clear();
        formAnswerDaoConfig.getIdentityScope().clear();
        formItemAnswerDaoConfig.getIdentityScope().clear();
        formTempDaoConfig.getIdentityScope().clear();
        attachFileDaoConfig.getIdentityScope().clear();
        formQuestionGroupDaoConfig.getIdentityScope().clear();
        formQuestionGroupFormDaoConfig.getIdentityScope().clear();
    }

    public DeviceSettingDao getDeviceSettingDao() {
        return deviceSettingDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserPermissionDao getUserPermissionDao() {
        return userPermissionDao;
    }

    public AppUserDao getAppUserDao() {
        return appUserDao;
    }

    public ChatGroupDao getChatGroupDao() {
        return chatGroupDao;
    }

    public ChatGroupMemberDao getChatGroupMemberDao() {
        return chatGroupMemberDao;
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

    public ComplaintReportDao getComplaintReportDao() {
        return complaintReportDao;
    }

    public SurveyFormDao getSurveyFormDao() {
        return surveyFormDao;
    }

    public SurveyFormQuestionDao getSurveyFormQuestionDao() {
        return surveyFormQuestionDao;
    }

    public SurveyFormQuestionTempDao getSurveyFormQuestionTempDao() {
        return surveyFormQuestionTempDao;
    }

    public FormDao getFormDao() {
        return formDao;
    }

    public FormQuestionDao getFormQuestionDao() {
        return formQuestionDao;
    }

    public FormAnswerDao getFormAnswerDao() {
        return formAnswerDao;
    }

    public FormItemAnswerDao getFormItemAnswerDao() {
        return formItemAnswerDao;
    }

    public FormTempDao getFormTempDao() {
        return formTempDao;
    }

    public AttachFileDao getAttachFileDao() {
        return attachFileDao;
    }

    public FormQuestionGroupDao getFormQuestionGroupDao() {
        return formQuestionGroupDao;
    }

    public FormQuestionGroupFormDao getFormQuestionGroupFormDao() {
        return formQuestionGroupFormDao;
    }

}
