package com.gap.pino_copy.db.objectmodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.List;

/**
 * Entity mapped to table "CHAT_GROUP_MEMBER".
 */
public class ChatGroupMember {

    private Long id;
    private Integer privilegeTypeEn;
    private Boolean adminIs;
    private Long appUserId;
    private Long chatGroupId;

    private transient List<Long> notAppUserIdList;
    private transient AppUser appUser;

    public ChatGroupMember() {
    }

    public ChatGroupMember(Long id) {
        this.id = id;
    }

    public ChatGroupMember(Long id, Integer privilegeTypeEn, Boolean adminIs, Long appUserId, Long chatGroupId) {
        this.id = id;
        this.privilegeTypeEn = privilegeTypeEn;
        this.adminIs = adminIs;
        this.appUserId = appUserId;
        this.chatGroupId = chatGroupId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPrivilegeTypeEn() {
        return privilegeTypeEn;
    }

    public void setPrivilegeTypeEn(Integer privilegeTypeEn) {
        this.privilegeTypeEn = privilegeTypeEn;
    }

    public Boolean getAdminIs() {
        return adminIs;
    }

    public void setAdminIs(Boolean adminIs) {
        this.adminIs = adminIs;
    }

    public Long getAppUserId() {
        return appUserId;
    }

    public void setAppUserId(Long appUserId) {
        this.appUserId = appUserId;
    }

    public Long getChatGroupId() {
        return chatGroupId;
    }

    public void setChatGroupId(Long chatGroupId) {
        this.chatGroupId = chatGroupId;
    }

    public List<Long> getNotAppUserIdList() {
        return notAppUserIdList;
    }

    public void setNotAppUserIdList(List<Long> notAppUserIdList) {
        this.notAppUserIdList = notAppUserIdList;
    }

    public AppUser getAppUser() {
        return appUser;
    }

    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }
}
