package com.gap.pino_copy.db.objectmodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "COMPLAINT_REPORT".
 */
public class ComplaintReport implements Parcelable {

    private Long id;
    private String identifier;
    private Long entityId;
    private Integer entityNameEn;
    private String displayName;
    private String reportCode;
    private String reportStr;
    private Long userReportId;
    private java.util.Date reportDate;
    private Long serverId;
    private Boolean deliverIs;
    private java.util.Date deliverDate;
    private Integer sendingStatusEn;
    private java.util.Date sendingStatusDate;
    private String xLatitude;
    private String yLongitude;

    public ComplaintReport() {
    }

    public ComplaintReport(Long id) {
        this.id = id;
    }

    public ComplaintReport(Long id, String identifier, Long entityId, Integer entityNameEn, String displayName, String reportCode, String reportStr, Long userReportId, java.util.Date reportDate, Long serverId, Boolean deliverIs, java.util.Date deliverDate, Integer sendingStatusEn, java.util.Date sendingStatusDate, String xLatitude, String yLongitude) {
        this.id = id;
        this.identifier = identifier;
        this.entityId = entityId;
        this.entityNameEn = entityNameEn;
        this.displayName = displayName;
        this.reportCode = reportCode;
        this.reportStr = reportStr;
        this.userReportId = userReportId;
        this.reportDate = reportDate;
        this.serverId = serverId;
        this.deliverIs = deliverIs;
        this.deliverDate = deliverDate;
        this.sendingStatusEn = sendingStatusEn;
        this.sendingStatusDate = sendingStatusDate;
        this.xLatitude = xLatitude;
        this.yLongitude = yLongitude;
    }

    protected ComplaintReport(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        identifier = in.readString();
        if (in.readByte() == 0) {
            entityId = null;
        } else {
            entityId = in.readLong();
        }
        if (in.readByte() == 0) {
            entityNameEn = null;
        } else {
            entityNameEn = in.readInt();
        }
        displayName = in.readString();
        reportCode = in.readString();
        reportStr = in.readString();
        if (in.readByte() == 0) {
            userReportId = null;
        } else {
            userReportId = in.readLong();
        }
        if (in.readByte() == 0) {
            serverId = null;
        } else {
            serverId = in.readLong();
        }
        byte tmpDeliverIs = in.readByte();
        deliverIs = tmpDeliverIs == 0 ? null : tmpDeliverIs == 1;
        if (in.readByte() == 0) {
            sendingStatusEn = null;
        } else {
            sendingStatusEn = in.readInt();
        }
        xLatitude = in.readString();
        yLongitude = in.readString();
    }

    public static final Creator<ComplaintReport> CREATOR = new Creator<ComplaintReport>() {
        @Override
        public ComplaintReport createFromParcel(Parcel in) {
            return new ComplaintReport(in);
        }

        @Override
        public ComplaintReport[] newArray(int size) {
            return new ComplaintReport[size];
        }
    };

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public Integer getEntityNameEn() {
        return entityNameEn;
    }

    public void setEntityNameEn(Integer entityNameEn) {
        this.entityNameEn = entityNameEn;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getReportCode() {
        return reportCode;
    }

    public void setReportCode(String reportCode) {
        this.reportCode = reportCode;
    }

    public String getReportStr() {
        return reportStr;
    }

    public void setReportStr(String reportStr) {
        this.reportStr = reportStr;
    }

    public Long getUserReportId() {
        return userReportId;
    }

    public void setUserReportId(Long userReportId) {
        this.userReportId = userReportId;
    }

    public java.util.Date getReportDate() {
        return reportDate;
    }

    public void setReportDate(java.util.Date reportDate) {
        this.reportDate = reportDate;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public Boolean getDeliverIs() {
        return deliverIs;
    }

    public void setDeliverIs(Boolean deliverIs) {
        this.deliverIs = deliverIs;
    }

    public java.util.Date getDeliverDate() {
        return deliverDate;
    }

    public void setDeliverDate(java.util.Date deliverDate) {
        this.deliverDate = deliverDate;
    }

    public Integer getSendingStatusEn() {
        return sendingStatusEn;
    }

    public void setSendingStatusEn(Integer sendingStatusEn) {
        this.sendingStatusEn = sendingStatusEn;
    }

    public java.util.Date getSendingStatusDate() {
        return sendingStatusDate;
    }

    public void setSendingStatusDate(java.util.Date sendingStatusDate) {
        this.sendingStatusDate = sendingStatusDate;
    }

    public String getXLatitude() {
        return xLatitude;
    }

    public void setXLatitude(String xLatitude) {
        this.xLatitude = xLatitude;
    }

    public String getYLongitude() {
        return yLongitude;
    }

    public void setYLongitude(String yLongitude) {
        this.yLongitude = yLongitude;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        if (id == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(id);
        }
        parcel.writeString(identifier);
        if (entityId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(entityId);
        }
        if (entityNameEn == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeInt(entityNameEn);
        }
        parcel.writeString(displayName);
        parcel.writeString(reportCode);
        parcel.writeString(reportStr);
        if (userReportId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(userReportId);
        }
        if (serverId == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(serverId);
        }
        parcel.writeByte((byte) (deliverIs == null ? 0 : deliverIs ? 1 : 2));
        if (sendingStatusEn == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeInt(sendingStatusEn);
        }
        parcel.writeString(xLatitude);
        parcel.writeString(yLongitude);
    }
}
