package com.gap.pino_copy.db.objectmodel;

import com.gap.pino_copy.db.dao.DaoSession;
import com.gap.pino_copy.db.dao.SurveyFormQuestionDao;
import com.gap.pino_copy.db.dao.SurveyFormQuestionTempDao;

import java.util.List;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURVEY_FORM_QUESTION".
 */
public class SurveyFormQuestion {

    private Long id;
    private String question;
    private Integer answerTypeEn;
    private Integer answerInt;
    private String answerStr;
    private Long serverAnswerId;
    private Long formQuestionGroupId;
    private String inputValuesDefault;
    private Long surveyFormId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SurveyFormQuestionDao myDao;

    private List<SurveyFormQuestionTemp> surveyFormQuestionTempList;

    public SurveyFormQuestion() {
    }

    public SurveyFormQuestion(Long id) {
        this.id = id;
    }

    public SurveyFormQuestion(Long id, String question, Integer answerTypeEn, Integer answerInt, String answerStr, Long serverAnswerId, Long formQuestionGroupId, String inputValuesDefault, Long surveyFormId) {
        this.id = id;
        this.question = question;
        this.answerTypeEn = answerTypeEn;
        this.answerInt = answerInt;
        this.answerStr = answerStr;
        this.serverAnswerId = serverAnswerId;
        this.formQuestionGroupId = formQuestionGroupId;
        this.inputValuesDefault = inputValuesDefault;
        this.surveyFormId = surveyFormId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSurveyFormQuestionDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public Integer getAnswerTypeEn() {
        return answerTypeEn;
    }

    public void setAnswerTypeEn(Integer answerTypeEn) {
        this.answerTypeEn = answerTypeEn;
    }

    public Integer getAnswerInt() {
        return answerInt;
    }

    public void setAnswerInt(Integer answerInt) {
        this.answerInt = answerInt;
    }

    public String getAnswerStr() {
        return answerStr;
    }

    public void setAnswerStr(String answerStr) {
        this.answerStr = answerStr;
    }

    public Long getServerAnswerId() {
        return serverAnswerId;
    }

    public void setServerAnswerId(Long serverAnswerId) {
        this.serverAnswerId = serverAnswerId;
    }

    public Long getFormQuestionGroupId() {
        return formQuestionGroupId;
    }

    public void setFormQuestionGroupId(Long formQuestionGroupId) {
        this.formQuestionGroupId = formQuestionGroupId;
    }

    public String getInputValuesDefault() {
        return inputValuesDefault;
    }

    public void setInputValuesDefault(String inputValuesDefault) {
        this.inputValuesDefault = inputValuesDefault;
    }

    public Long getSurveyFormId() {
        return surveyFormId;
    }

    public void setSurveyFormId(long surveyFormId) {
        this.surveyFormId = surveyFormId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SurveyFormQuestionTemp> getSurveyFormQuestionTempList() {
        if (surveyFormQuestionTempList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SurveyFormQuestionTempDao targetDao = daoSession.getSurveyFormQuestionTempDao();
            List<SurveyFormQuestionTemp> surveyFormQuestionTempListNew = targetDao._querySurveyFormQuestion_SurveyFormQuestionTempList(id);
            synchronized (this) {
                if(surveyFormQuestionTempList == null) {
                    surveyFormQuestionTempList = surveyFormQuestionTempListNew;
                }
            }
        }
        return surveyFormQuestionTempList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSurveyFormQuestionTempList() {
        surveyFormQuestionTempList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
