package com.gap.pino_copy.db.objectmodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_PERMISSION".
 */
public class UserPermission {

    private Long id;
    private String permissionName;
    private Long userId;

    public UserPermission() {
    }

    public UserPermission(Long id) {
        this.id = id;
    }

    public UserPermission(Long id, String permissionName, Long userId) {
        this.id = id;
        this.permissionName = permissionName;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPermissionName() {
        return permissionName;
    }

    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
